experiment 31 : xgboost + dataset 3 + default hyperparameter

Traceback (most recent call last):
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 827, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/home/m448735/anaconda3/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "node_2.py", line 10, in <module>
    experiments.exp_default(
  File "/home/m448735/hyperparameter-tuning-benchmark/experiments.py", line 19, in exp_default
    hasil=opt.no_optimizer(X,y,kwargs["model"],kwargs["eval_method"])
  File "/home/m448735/hyperparameter-tuning-benchmark/services/optimizer.py", line 17, in no_optimizer
    cv_results = cross_validate(model,X,y,cv=skf,scoring=eval_method)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 838, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 242, in <genexpr>
    scores = parallel(
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 336, in split
    for train, test in super().split(X, y, groups):
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 80, in split
    for test_index in self._iter_test_masks(X, y, groups):
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 697, in _iter_test_masks
    test_folds = self._make_test_folds(X, y)
  File "/home/m448735/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 649, in _make_test_folds
    raise ValueError(
ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.
srun: error: komputasi07: task 0: Exited with exit code 1
